version: '3'
name: finya

networks:
  finya-net:
    driver: bridge

services:
  finya_postgres:
    container_name: finya_postgres
    image: postgres:15.3-alpine3.18
    restart: always
    networks:
      - finya-net
    ports:
      - 5432:5432

    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=finya
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  finya_pgadmin:
    container_name: finya_pgadmin
    image: dpage/pgadmin4:8.6
    restart: always
    networks:
      - finya-net
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=admin

