name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      
    - name: Lint    
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest
        args: --timeout 5m
      
    - name: Build
      run: |
            go mod tidy
            go build -v ./...
    
    - name: Run tests
      run: go test -v ./...